name: Build Image
on:
  push:
    branches: [ "master", "main" ]
    tags-ignore:
      - "*"
    paths-ignore:
      - docs/**
      - .github/**
      - "**.md"
      - LICENSE
      - .*ignore
      - .gitattributes
      - .editorconfig
      - .gitmodules
      - .idea/**
      - .vscode/**
      - distribution/**
env:
  namespace: ${{ github.repository_owner }}
permissions: write-all
jobs:
  build-image:
    runs-on:
      ubuntu-latest
    timeout-minutes: 360 # 6 hours
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
      - name: Install regctl
        uses: regclient/actions/regctl-installer@main
      - name: regctl login
        uses: regclient/actions/regctl-login@main
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Docker
        uses: docker/setup-docker-action@v4
        with:
          daemon-config: |
            {
              "debug": true,
              "features": {
                "containerd-snapshotter": true
              }
            }
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          build-scan-publish: false
      - name: Generate CI Version
        # TODO: add an gradle compile option to set version from the CI
        run: |
          chmod +x gradlew
          version=$(./gradlew -q -Dci=false :version)
          echo "version_name=${version}" >> $GITHUB_ENV
          echo "remote_tag=${version}" >> $GITHUB_ENV
        id: project_version
      - name: Install Dependencies
        run: |
          git clone https://github.com/roll-w/web-common-starter 
          cd web-common-starter
          git checkout v0.2.1
          mvn -f web-common-parent/ clean install
          cd ..
      - name: Install Frontend Dependencies
        run: |
          cd lampray-frontend
          npm install
      - name: Package Images
        run: |
          chmod +x gradlew
          ./gradlew -Dci=true -PbuildFrontend=true packageImageMultiArch
      - name: Upload Dist
        uses: actions/upload-artifact@v4
        with:
          name: lampray-${{ env.version_name }}-dist.tar.gz
          path: build/dist/lampray-${{ env.version_name }}-dist.tar.gz
      - name: Upload Image Archives (Amd64)
        uses: actions/upload-artifact@v4
        with:
          name: lampray-${{ env.version_name }}-amd64-image
          path: |
            build/dist/lampray-${{ env.version_name }}-amd64-image.tar.gz
      - name: Upload Image Archives (Arm64)
        uses: actions/upload-artifact@v4
        with:
          name: lampray-${{ env.version_name }}-arm64-image
          path: |
            build/dist/lampray-${{ env.version_name }}-arm64-image.tar.gz
      - name: Push Image
        run: |
          if [ "${{ github.event_name }}" == "push" ]; then
            echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            regctl image import ocidir://build/dist/oci-layout:amd64 build/dist/lampray-${{ env.version_name }}-amd64-image.tar.gz
            regctl image import ocidir://build/dist/oci-layout:arm64 build/dist/lampray-${{ env.version_name }}-arm64-image.tar.gz

            regctl index create ghcr.io/${{ env.namespace }}/lampray:${{ env.version_name }} \
              --ref ocidir://build/dist/oci-layout:amd64 \
              --ref ocidir://build/dist/oci-layout:arm64 \
              --annotation org.opencontainers.image.authors=rollw \
              --annotation org.opencontainers.image.title=Lampray \
              --annotation org.opencontainers.image.description="Lampray is a blog system based on Spring Boot 3 framework." \
              --annotation org.opencontainers.image.url="https://github.com/roll-w/lampray" \
              --annotation org.opencontainers.image.source="https://github.com/roll-w/lampray" \
              --annotation org.opencontainers.image.version=${{ env.version_name }} \
              --annotation org.opencontainers.image.licenses=Apache-2.0 \
              --annotation org.opencontainers.image.vendor=RollW \
              --annotation org.opencontainers.image.documentation="https://github.com/roll-w/lampray/blob/main/README.md"
          
            regctl image copy ghcr.io/${{ env.namespace }}/lampray:${{ env.version_name }} ghcr.io/${{ env.namespace }}/lampray:main
          fi

      - name: Output Result
        run: |
          echo "# Build Summary" >> $GITHUB_STEP_SUMMARY
          echo '- Version: `${{ env.version_name }}`' >> $GITHUB_STEP_SUMMARY
          echo '- Remote Tag: `${{ env.remote_tag }}`, `main`' >> $GITHUB_STEP_SUMMARY
          echo '' >> $GITHUB_STEP_SUMMARY
          echo "Image has been pushed, run the following command to pull the image:" >> $GITHUB_STEP_SUMMARY
          echo '' >> $GITHUB_STEP_SUMMARY
          echo '```bash' >> $GITHUB_STEP_SUMMARY
          echo "docker pull ghcr.io/${{ env.namespace }}/lampray:${{ env.remote_tag }}" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          echo '' >> $GITHUB_STEP_SUMMARY
          echo 'You can also download the image package from the artifacts, and run command like following to load the image:' >> $GITHUB_STEP_SUMMARY
          echo '' >> $GITHUB_STEP_SUMMARY
          echo '```bash' >> $GITHUB_STEP_SUMMARY
          echo "docker load -i lampray-${{ env.remote_tag }}-amd64-image.tar.gz" >> $GITHUB_STEP_SUMMARY
          echo "docker load -i lampray-${{ env.remote_tag }}-arm64-image.tar.gz" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          echo '' >> $GITHUB_STEP_SUMMARY
          echo '' >> $GITHUB_STEP_SUMMARY
