name: Dependency Submission
on:
  push:
    branches: [ "master", "main" ]
    tags-ignore:
      - "*"
    paths-ignore:
      - docs/**
      - .github/**
      - "**.md"
      - LICENSE
      - .*ignore
      - .gitattributes
      - .editorconfig
      - .gitmodules
      - .idea/**
      - .vscode/**
      - distribution/**
permissions:
  contents: write
jobs:
  dependency-submission:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Install Dependencies
        run: |
          git clone https://github.com/roll-w/web-common-starter 
          cd web-common-starter
          git checkout v0.2.1
          mvn -f web-common-parent/ clean install
          cd ..
      - name: Submit Dependency Graph
        uses: gradle/actions/dependency-submission@v4
